### PR TITLE
Add manual submit button

### PR DESCRIPTION
**Pull request by itsluminous**
The issue reported by most people is that it is not automatically pushing code to git.
This is happening because the observer is not working properly to add an event on submit button.
So, providing a manual submit button is easiest option.

I had to use mouseenter for manual submit button because if we use click, then url changes and we don't have submission id anymore.

### CODE REVIEW

**Comment by raphaelheinz** [comment]
Hi @itsluminous,
great! Thanks a lot for your pull request. I only added minor changes. Besides, I delayed the mouseenter event for 750ms because every time I accidentally hovered with my mouse over the button, the confirmation dialog was opened..I will merge this into master soon. This should also solve #19. Thanks!

**Review by raphaelheinz — APPROVED** [review]

**Comment by itsluminous** [comment]
750ms feels like too long to wait though.
Users might click if it does not do anything on hover for so long, and that will break the functionality.

I feel that a wait of like 300ms should be good enough.

**Comment by raphaelheinz** [comment]
Yes, I agree. I updated in a35dea444195b71a7dfa6a421d22e44efbba7321

**Comment by itsluminous** [comment]
great!
thanks

**Pull request merged**
