### PR TITLE
Add submit icon only if notes icon is present

### PR DESCRIPTION
**Pull request by itsluminous**

### CODE REVIEW

**Comment by itsluminous** [comment]
Should fix #26

**Comment by raphaelheinz** [comment]
https://github.com/itsluminous/LeetHub-3.0-Submit/blob/b1076c9735c85518a02e2c8b3bf02fab61b1573c/scripts/leetcode.js#L967-L968

In my case, the bookmark icon is at index 1 - not at index 0. Therefore, the manual push button is not displayed. Please see the screenshot below.

image


However, the button is visible, if I access at index 1. But this will probably break it on your side, correct?

I think we should be safe if we loop through all children and check if any icon is of type bookmark. What do you think?

**Comment by itsluminous** [comment]
my bad, I did not push latest
please check now

the index issue happens with languages like C#
in c# we don't get "format" icon

**Comment by raphaelheinz** [comment]
Thanks @itsluminous for your help! I merged into main branch.

**Pull request merged**
